# 1d Array
* Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
* Calculate the sum and average of the array elements.
* Multiply the array by a scalar value of 3.
* Slice the array to select elements from the 3rd to the 7th position.
* Compute the sum and average of the sliced array

In [2]:

import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Sum of arr : ", np.sum(a)) 
print("Average of arr : ", np.average(a)) 
print("Multipliacation  of arr  by 3: ", a*3) 
print("Slice the array to select elements from the 3rd to the 7th position:",a[2:7])
print("sum and average of sliced array:",np.sum(a[2:7]))
print("Average of sliced array:",np.average(a[2:7]))

Sum of arr :  55
Average of arr :  5.5
Multipliacation  of arr  by 3:  [ 3  6  9 12 15 18 21 24 27 30]
Slice the array to select elements from the 3rd to the 7th position: [3 4 5 6 7]
sum and average of sliced array: 25
Average of sliced array: 5.0


# Multi-dimensional array
* Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}
* Print the element in the second row, third column.
* Print the second row
* Print the second column
* Compute the transpose of the matrix'''

In [3]:

matrixArray=np.matrix([[3,4,5],[6,7,8],[9,1,2]])
print("Element in 2nd row 3rd column:", matrixArray[1,2])
print("Print the second row:", matrixArray[1,:3])
print("Print second column:",matrixArray[:,1])
print("Transpose of the matrix:", matrixArray.transpose())

Element in 2nd row 3rd column: 8
Print the second row: [[6 7 8]]
Print second column: [[4]
 [7]
 [1]]
Transpose of the matrix: [[3 6 9]
 [4 7 1]
 [5 8 2]]


# Concatenation
* Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]
* Concatenate the two arrays
* Sort the new array from lowest to highest
* Split the result from the previous step into two equal sized arrays




In [4]:
a1=np.array([5,1,4,2])
a2=np.array([6,10,11,7])
newArray=np.concatenate([a1,a2])
sortArray=np.sort(newArray)
print("Concatenate two arrays:", newArray)
print("Sort arrays from lowest to highest:",sortArray)
print("Split the array:", np.array_split(sortArray, 2))

Concatenate two arrays: [ 5  1  4  2  6 10 11  7]
Sort arrays from lowest to highest: [ 1  2  4  5  6  7 10 11]
Split the array: [array([1, 2, 4, 5]), array([ 6,  7, 10, 11])]


# Mathematical functions
* Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
* Compute an array that applies the mathematical sin function to the original array
* Do the same for the following mathematical functions: cos, log, exp
* Compute the mean, median, and standard deviation of each resultant array

In [5]:
import math
valuesArray=np.arange(0,(math.pi*4+math.pi/2),math.pi/2)
print(valuesArray)
print("mean:", np.mean(valuesArray))
print("medium:", np.median(valuesArray))
print("standard deviation:", np.std(valuesArray))
sinArray=np.sin(valuesArray)
cosArray=np.cos(valuesArray)
logArray=np.log(valuesArray)
expArray=np.exp(valuesArray)
print(" Sin function:", sinArray)
print("mean of sinArray:", np.mean(sinArray))
print("medium of SinArray:", np.median(sinArray))
print("standard deviation of sinArray:", np.std(sinArray))
print("cos function:", cosArray)
print("mean of cosArray:", np.mean(cosArray))
print("medium of cosArray:", np.median(cosArray))
print("standard deviation of cosArray:", np.std(cosArray))
print("log function:", logArray)
print("mean of logArray:", np.mean(logArray))
print("medium of logArray:", np.median(logArray))
print("standard deviation of logArray:", np.std(logArray))
print("exp value: ",expArray)
print("mean of expArray:", np.mean(expArray))
print("medium of expArray:", np.median(expArray))
print("standard deviation of expArray:", np.std(expArray))











[ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061]
mean: 6.283185307179587
medium: 6.283185307179586
standard deviation: 4.055778675973612
 Sin function: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16  1.0000000e+00  3.6739404e-16 -1.0000000e+00
 -4.8985872e-16]
mean of sinArray: -2.975712385932333e-17
medium of SinArray: 0.0
standard deviation of sinArray: 0.6666666666666666
cos function: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00  3.0616170e-16 -1.0000000e+00 -4.2862638e-16
  1.0000000e+00]
mean of cosArray: 0.11111111111111106
medium of cosArray: 6.123233995736766e-17
standard deviation of cosArray: 0.7370277311900889
log function: [      -inf 0.45158271 1.14472989 1.55019499 1.83787707 2.06102062
 2.24334217 2.39749285 2.53102425]
mean of logArray: -inf
medium of logArray: 1.8378770664093453
standard deviation of logArray: nan
exp value:  [1.00000000e+00 4.810

/var/folders/7s/7j9cxlw57jz9dscyz4mx7p780000gn/T/ipykernel_1155/3368016497.py:9: RuntimeWarning: divide by zero encountered in log
  logArray=np.log(valuesArray)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/_methods.py:173: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


# Boolean Indexing and Filtering
* Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
* Create a boolean array that identifies elements which are greater than 25
* Use that boolean array to filter out elements greater than 25 from the original array.

In [6]:
multicationArray=np.arange(15,80,5)
multicationArray=np.append(multicationArray,12)
print(multicationArray)
boolenArray=multicationArray>25
print(boolenArray)
print(multicationArray[~boolenArray])

[15 20 25 30 35 40 45 50 55 60 65 70 75 12]
[False False False  True  True  True  True  True  True  True  True  True
  True False]
[15 20 25 12]
